name: Generate READMEs

on:
  workflow_dispatch:
    inputs:
      python_version:
        description: 'Python version to use'
        required: false
        default: '3.11'

jobs:
  generate-readmes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ github.event.inputs.python_version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Run generate_readmes.py
        run: |
          python generate_readmes.py
