name: Deploy

on:
  push:
    branches:
      - test
      - sit
      - uat

#env:
#  pgdb_credid: ${{ secrets.BRANCH_NAME_pgdb_credid_ui }}
#  pgdb_url: ${{ secrets.BRANCH_NAME_pfzalgn_pgdb_url }}
#  unix_server: ${{ secrets.BRANCH_NAME_pfzalgn_unix_server }}
#  snowflake_COMETL_CONTROL__db_url: ${{ secrets.BRANCH_NAME_pfzalgn_snowflake_COMETL_CONTROL_db_url_grw }}
#  snowflake_COMETL_PA__db_url: ${{ secrets.BRANCH_NAME_pfzalgn_snowflake_COMETL_PA_db_url_grw }}
#  snowflake_credid_COMETL_CONTROL: ${{ secrets.BRANCH_NAME_pfzalgn_COMETL_CONTROL_snowflake_credid_grw }}
#  snowflake_credid_COMETL_PA: ${{ secrets.BRANCH_NAME_pfzalgn_COMETL_PA_snowflake_credid_grw }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set environment variables
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/test" ]]; then
            echo "export ENVIRONMENT=test" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/sit" ]]; then
            echo "export ENVIRONMENT=sit" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/uat" ]]; then
            echo "export ENVIRONMENT=uat" >> $GITHUB_ENV
          else
            echo "Invalid branch."
            exit 1
          fi

      - name: Debug
        run: |
          echo "ENVIRONMENT: ${{ env.ENVIRONMENT }}"
          echo "Modified Files:"
          git diff-tree --no-commit-id --name-only -r ${{ github.sha }}

      - name: Deploy to PostgreSQL
        if: ${{ env.ENVIRONMENT == 'test' || env.ENVIRONMENT == 'sit' || env.ENVIRONMENT == 'uat' && contains(github.event.head_commit.modified, 'postgres/') }}
        run: |
          echo "Deploying to PostgreSQL environment: ${{ env.ENVIRONMENT }}"
          # Add your PostgreSQL deployment logic here
          # You can use the environment variables: ${{ env.pgdb_credid }}, ${{ env.pgdb_url }}

      - name: Deploy to Unix
        if: ${{ env.ENVIRONMENT == 'test' || env.ENVIRONMENT == 'sit' || env.ENVIRONMENT == 'uat' }}
        run: |
          echo "Deploying to Unix environment: ${{ env.ENVIRONMENT }}"
          # Add your Unix deployment logic here
          # You can use the environment variables: ${{ env.unix_server }}

      - name: Deploy to Snowflake Database - COMETL_CONTROL
        if: ${{ env.ENVIRONMENT == 'test' || env.ENVIRONMENT == 'sit' || env.ENVIRONMENT == 'uat' }}
        run: |
          echo "Deploying to Snowflake COMETL_CONTROL environment: ${{ env.ENVIRONMENT }}"
          # Add your Snowflake COMETL_CONTROL deployment logic here
          # You can use the environment variables: ${{ env.snowflake_COMETL_CONTROL__db_url }}, ${{ env.snowflake_credid_COMETL_CONTROL }}

      - name: Deploy to Snowflake Database - COMETL_PA
        if: ${{ env.ENVIRONMENT == 'test' || env.ENVIRONMENT == 'sit' || env.ENVIRONMENT == 'uat' }}
        run: |
          echo "Deploying to Snowflake COMETL_PA environment: ${{ env.ENVIRONMENT }}"
          # Add your Snowflake COMETL_PA deployment logic here
          # You can use the environment variables: ${{ env.snowflake_COMETL_PA__db_url }}, ${{ env.snowflake_credid_COMETL_PA }}
