name: Deploy

on:
  push:
    branches:
      - test
      - sit
      - uat


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set environment variables
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/test" ]]; then
            echo "ENVIRONMENT=test" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/sit" ]]; then
            echo "ENVIRONMENT=sit" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/uat" ]]; then
            echo "ENVIRONMENT=uat" >> $GITHUB_ENV
          else
            echo "Invalid branch."
            exit 1
          fi

      - name: Check folder changes
        id: folder_changes
        run: |
          if git diff-tree --name-only --no-commit-id ${{ github.event.before }} ${{ github.sha }} | grep -q "postgres/"; then
            echo "Folder changes detected"
            echo "folder_changed=true" >> $GITHUB_ENV
          else
            echo "No folder changes"
            echo "folder_changed=false" >> $GITHUB_ENV
          fi
      - name: Deploy stage
        if: steps.folder_changes.outputs.folder_changed == 'true'
        run: |
          echo "Deploying to PostgreSQL environment: $ENVIRONMENT"
          # Add your PostgreSQL deployment logic here
          # You can use the environment variables: ${{ env.pgdb_credid }}, ${{ env.pgdb_url }}

      - name: Deploy to Unix
        if: ${{ env.ENVIRONMENT == 'test' || env.ENVIRONMENT == 'sit' || env.ENVIRONMENT == 'uat' }}
        run: |
          echo "Deploying to Unix environment: $ENVIRONMENT"
          # Add your Unix deployment logic here
          # You can use the environment variables: ${{ env.unix_server }}

      - name: Deploy to Snowflake Database - COMETL_CONTROL
        if: ${{ env.ENVIRONMENT == 'test' || env.ENVIRONMENT == 'sit' || env.ENVIRONMENT == 'uat' }}
        run: |
          echo "Deploying to Snowflake COMETL_CONTROL environment: $ENVIRONMENT"
          # Add your Snowflake COMETL_CONTROL deployment logic here
          # You can use the environment variables: ${{ env.snowflake_COMETL_CONTROL__db_url }}, ${{ env.snowflake_credid_COMETL_CONTROL }}

      - name: Deploy to Snowflake Database - COMETL_PA
        if: ${{ env.ENVIRONMENT == 'test' || env.ENVIRONMENT == 'sit' || env.ENVIRONMENT == 'uat' }}
        run: |
          echo "Deploying to Snowflake COMETL_PA environment: $ENVIRONMENT"
          # Add your Snowflake COMETL_PA deployment logic here
          # You can use the environment variables: ${{ env.snowflake_COMETL_PA__db_url }}, ${{ env.snowflake_credid_COMETL_PA }}
